### ISSUE TITLE
Any instruction on how to install?

### ISSUE THREAD

**Issue by andyrav** [oliverjrose99/recordurbate#1]
Any instruction on how to install?

**Comment by oliverjrose99** [comment]
Hi

This project currently sort of works sort of doesn't. I will be working on an update through out  the week and will push it out around Friday/Saturday. 

Current requirements are Linux, apache 2 with php (only tested on version 7) with access to exec and curl with https certificates. Put all of the files in the web directory. You will need to add a cron job to run the startRecord.php every minute or what ever interval. Using the web interface you can add and remove streamers using their username. It should then record the stream to the dir stated in the general configuration file. All recorded videos need to be ran through ffmpeg just to properly organize the mp4 file. I can't remember if the recording properly stops so just make sure the first couple of times.

The update should fix and automate many of these things.
