### ISSUE TITLE
Issues running --exec.

### ISSUE THREAD

**Issue by varunchopra** [oliverjrose99/Recordurbate#1]
I'm facing issues running `--exec`. 

If I give it a test run,

`youtube-dl https://chaturbate.com/modelname/ --config-location config.json --exec 'python3 test.py {}'`

it works perfectly, but it doesn't work when it's integrated with the script. Any idea what I'm doing wrong? :O

**Comment by oliverjrose99** [comment]
try changing test.py to a full path e.g.
```
--exec 'python3 /home/name/test.py {}'
```
in the youtube-dl.config

**Comment by varunchopra** [comment]
Tried this too. Is there any way to see a verbose output while it executes?

Edit -

Wait, what do you mean by changing the path in the youtube-dl.config?

Isn't the --exec switch passed along with the rest of the args?

**Comment by oliverjrose99** [comment]
not right now, all input and output from youtube-dl gets sent to /dev/null

**Comment by varunchopra** [comment]
Well, thanks.

I'll let you know if I figure out why it isn't working.

**Comment by oliverjrose99** [comment]
Im not sure what you've setup so ill just go over it.

In the configs folder there should be two files, config.json and youtube-dl.config. config.json is used by the bot and youtube-dl.config is passed to youtube-dl with the param `--config-location configs/youtube-dl.config`. Add the line `--exec 'python3 /home/name/test.py {}'` to the youtube-dl.config file after the line starting with -o. When the youtube-dl.config file is passed to yt-dl it treats it like command line options, [more exmaples here](https://github.com/rg3/youtube-dl#configuration).

**Comment by varunchopra** [comment]
I wasn't aware of that! Thanks!

Yep, that works. Great work mate!
