### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by sub-zer087** [oliverjrose99/Recordurbate#11]
First of all thank you for your script, 
when i try to install the version 2.0.0 it gives me the error 404, i needed to go to releases and install the older version 1.2.0.

**Comment by oliverjrose99** [comment]
haha sorry i forgot to update the release files, it should be fixed now. let me know.

**Comment by sub-zer087** [comment]
When i run ./Recordurbate.py 
it gives me this 
`./Recordurbate.py: line 1: import: command not found
from: can't read /var/mail/daemon
./Recordurbate.py: line 3: import: command not found
./Recordurbate.py: line 5: syntax error near unexpected token `('
./Recordurbate.py: line 5: `def usage():'
`
Im using a rpi 4 running raspbian, the version 1.2.0 is working well.

**Comment by oliverjrose99** [comment]
ok. all should be good now, i forgot the shebang and then had an issue with line endings.

**Comment by sub-zer087** [comment]
ok i did some tests, 
after ./Recordubate.py start or restart, in the console it prints the help, the daemon seems to start, after i add a streamer it doesn´t record, and in the proccess list the youtube-dl and ffmpeg never show up like in the previous version.
i will stay in the previous version for now.
Once again thank you.

edit: tried again with a new install and now the daemon doesnt seem to be starting anymore

**Comment by oliverjrose99** [comment]
serveral fixes later everything should now work, sorry for the issues.
