### ISSUE TITLE
could i use it on windows or android termux?

### ISSUE THREAD

**Issue by weigeloveu** [oliverjrose99/Recordurbate#16]
when i try use it on win or android some error code 
`Traceback (most recent call last):
  File "C:\Users\weige\Downloads\recordurbate\Recordurbate.py", line 3, in <module>
    from daemon import Daemon
  File "C:\Users\weige\Downloads\recordurbate\daemon.py", line 12, in <module>
    from bot import Bot
  File "C:\Users\weige\Downloads\recordurbate\bot.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by oliverjrose99** [comment]
That issue is becuase you dont have requests installed but the bot wont work on windows becuase it uses OS.fork() which doesn't support windows. As for android termux, I haven't tested it but it should work as android runs on linux.

**Comment by Rhade3000** [comment]
you can use windows 10 with a ubuntu subsystem, then invoke in bash. It works

**Comment by oliverjrose99** [comment]
Might as well run a vm at that point, a native solution would be better, I've seen that cygwin supports fork but can be unreliable.
