### ISSUE TITLE
bad interpreter: No such file or directory on termux

### ISSUE THREAD

**Issue by weigeloveu** [oliverjrose99/Recordurbate#17]
![Screenshot_2019-10-16-14-04-57-382_com termux](https://user-images.githubusercontent.com/19830500/66892705-07778000-efb2-11e9-95b5-a6a155fbb07c.jpg)
thanks your good script,if it could be run on termux it's very convenience for android user.
but when i try to run it,there some errors happen ed,any idea?

**Comment by oliverjrose99** [comment]
you need to install python3, im not sure if [this guide](https://wiki.termux.com/wiki/Python) is up to date but you can try it. dont forget `pip install requests` as well once python is installed. Recordurbate will eat through any data allowance you have and your network provider may block NSFW sites, just to let you know.

**Comment by oliverjrose99** [comment]
I've just tried it and found that python installs to a different location. You have to run it as `python Recordurbate.py [command] `
