### ISSUE TITLE
List with last broadcast date

### ISSUE THREAD

**Issue by cb123321** [oliverjrose99/Recordurbate#18]
Hello,
This is not a issue, I just want to ask if it's possible to add a command.
That I want is a list command that also check for last broadcast date, to use for decide to remove or keep.

I do this manually and it's pretty boring :)

//J

**Comment by oliverjrose99** [comment]
sure ill have a look into it. what would you want, a command like `./Recordurbate.py last [name]`, where name is optional and would print out the last date of that streamer and all streamers if name is not passed?

**Comment by cb123321** [comment]
A list with all would be good, like the list command with last broadcast date/time :+1:
