### ISSUE TITLE
starting and stopping constantly

### ISSUE THREAD

**Issue by BelgarionNL** [oliverjrose99/Recordurbate#21]
hi, installed debian on my unraid server and gave it plenty of cores + RAM.

* debian 10 already has python 3
* installed Youtube-dl ( sudo apt install youtube-dl )
* ffmpeg is also installed on debian

followed these steps:
wget https://github.com/oliverjrose99/Recordurbate/releases/download/2.0.4/recordurbate.tar
tar -xf recordurbate.tar
cd recordurbate
chmod +x Recordurbate.py

but instead of using ./Recordurbate help I use python3 Recordurbate.py help and it does the same thing.

the rest works fine I can start/stop/restart the script just fine it just stops and starts. 

can you recommend another distro that works for you?

**Comment by oliverjrose99** [comment]
Ive tested on ubuntu server which works fine. Please check logs e.g. rb.log and the security/os/auth logs, make sure you have python requests installed as well, check htop/running processes to see if the bot is still running after you start it.

**Comment by oliverjrose99** [comment]
@BelgarionNL Youtube-dl is currenrly broken, please watch for an update by them

**Comment by oliverjrose99** [comment]
Please see issue #23
