### ISSUE TITLE
"problem" with limit rate

### ISSUE THREAD

**Issue by sub-zer087** [oliverjrose99/Recordurbate#22]
hello, first and once again thank you for your awesome script.
i was triyng to increase the limit rate because i think a query to chaturbate every 5 seconds was a little to much, so i increase it to 60, (i use pihole so i can see the amount of querys to chaturbate and sometimes it goes up to 4000 or 5000 by day).
The problem is when i did this it takes about 3 to 5 minutes to start or stop the recording.
When i put it back to 5 everything went to normal.

**Comment by oliverjrose99** [comment]
the `rate_limit_time` option sets how many seconds to wait between checking if each streamer is online. the default of 5 is 5 seconds, 60 would be a minute, .1 would be 100ms, etc. if your getting blocked  by chaturbate i would recommend slowly increasing the time until it works fine. maybe start with 20, im not sure.

**Comment by sub-zer087** [comment]
ok, understood it.
Thank you
