### ISSUE TITLE
Loop Issue

### ISSUE THREAD

**Issue by ghost** [oliverjrose99/Recordurbate#24]
Version: 2.0.4
OS: Ubuntu 18.04

2019-11-15 12:28:18,311 - loop error
Traceback (most recent call last):
  File "/home/recordurbate/bot.py", line 125, in run
    self.processes.append([streamer[0], subprocess.Popen(args, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)])
AttributeError: 'module' object has no attribute 'DEVNULL'

**Comment by oliverjrose99** [comment]
This looks like an issue with the script running in python2.  Please make sure you have python3 installed and that the script runs with python3. what does the following commands print out, `python3 --version` and `python --version`
