### ISSUE TITLE
Used to work fine before. But not recording now.

### ISSUE THREAD

**Issue by monukoshy** [oliverjrose99/Recordurbate#29]
I have updated the youtube-dl to the latest version currently its at youtube-dl-2019.11.28
recordurbate used to work fine earlier, but for the past few weeks its not capturing streams.
I am able to successfully start the command, but no new media is captured.

Here's the logs.
https://pastebin.com/5357H52t

can you help resolve this please?

**Comment by oliverjrose99** [comment]
Please add the `rate_limit` option to your config.

**Comment by monukoshy** [comment]
thanks, but which file.. should i add this to? And which line.. I am sorry I am new to this. Is there a value to what i can set for rate_limit?

**Comment by oliverjrose99** [comment]
in the config.json file add the following lines:
"rate_limit": true,
"rate_limit_time": 5

**Comment by monukoshy** [comment]
Amazing, no more errors, now have to see when folks get online and it downloads the streams.
Please do not close the ticket yet.. give me a day or two to report back.
Was this a bug? I mean, do u plan to add these two lines into the config file in the next update?

**Comment by oliverjrose99** [comment]
its my fault, the way the script gets config values isn't very good, it'll get changed at some point. the values should be in new downloads of the script.

**Comment by monukoshy** [comment]
The scripts keeps crashing, I mean when i execute the command 
./Recordurbate.py start
The rd.log file stays the daemon has started, but then it does not run.. I mean when i run the command 
ps -ef | grep Recordurbate.py
I dont see any processes by Recordurbate
I dont see any errors in the logs after the message that the daemon has started.

I am going to re-download your script from git, and try.
In the mean time can u check if its working? If u can download the new git files and try with that.?

**Comment by monukoshy** [comment]
All your files are having Ctl+M (^M) characters at the end of the line bro.

**Comment by monukoshy** [comment]
Currently working on removing these in vi editor using 
:%s/^M//g

The escape chars are in all the files in each sub folder. I wonder replacing them with the above string does not break the code. :(

**Comment by monukoshy** [comment]
So I wanted to update you. After removing those escape chars from the scripts, the recordurbate is now working fine. Thank you so much for helping with this. This ticket can now be closed. Keep up the good work bro. Thanks for all your hard work.

**Comment by vold4545** [comment]
I have installed the script and started the python file. Logs shows not error and states started recording. But, it does not create any folder or file of the recorded content. any idea? Its running on a RaspberryPi

**Comment by oliverjrose99** [comment]
@vold4545 Please run `pip3 install -U youtube-dl` or `python3 pip install -U youtube-dl` to upgrade youtube-dl to the latest version and report back

**Comment by oliverjrose99** [comment]
@monukoshy Thanks for the info. Oddly I found that on a Ubuntu droplet from DO i get no issues with line endings although i've had issues in the past but they were fixed.

**Comment by vold4545** [comment]
it worked, thanks.
