### ISSUE TITLE
No errors in logs but no download file

### ISSUE THREAD

**Issue by xxdan69** [oliverjrose99/Recordurbate#32]
The deamon run without any problem but no files are downloaded. I see the "Started to record" and "Stop to record" but no files

**Comment by xxdan69** [comment]
After some search it seams to come from youtube-dl.
I added a line in bot.py and one in config.json. 

bot.py
-----------
                       args = [self.config["youtube-dl_cmd"],  # youtube-dl bin
                                "https://chaturbate.com/{}/".format(streamer[0]),  # chaturbate url
                                "--config-location", self.config["youtube-dl_config"],   # youtube-dl config
                                "--add-header", self.config["youtube-dl_header"]] #youtube-dl arg for chaturbate compatibility
-----------

config.json
-----------
"youtube-dl_header": "Cookie:cb_legacy=1",
-----------

**Comment by oliverjrose99** [comment]
please check have youtube-dl updated to the lastest version.
