### ISSUE TITLE
No recordings are being made due to cloudflare

### ISSUE THREAD

**Issue by Keruli** [oliverjrose99/Recordurbate#34]
No new recordings are being made. It looks like chaturbate have added cloudflare. 

On line 75 of bot.py, when the online status is checked, the following error occurs:
```
2020-01-12 22:08:39,230 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/pah/to/bot.py", line 76, in is_online
    if r.json()["room_status"] == "public":
...
```

Upon logging the source of the page downloaded by the post query the source contains a cloudflare captcha due to suspected bot activity.

Any way to get around this?

**Comment by oliverjrose99** [comment]
if your using the latest version you can use the `rate_limit_time` and `rate_limit` options to put a delay between chaturbate calls. you may need to wait some time for the cloudflare block to pass or you can do the captcha your self which may fix it

**Comment by Keruli** [comment]
Thanks for the speedy reply! I'll add the rate limit now.

How do I go about doing the captcha myself?

**Comment by oliverjrose99** [comment]
open chaturbate in a browser, it should give you the prompt/warning page

**Comment by Keruli** [comment]
Hmm, even when I complete the captcha in a browser it still gets the page in the program. I guess because the cookies are different or something. Any suggestions?
