### ISSUE TITLE
Recording start-stop every minute and not saving videos...

### ISSUE THREAD

**Issue by emalov98ffm** [oliverjrose99/Recordurbate#35]

**Comment by emalov98ffm** [comment]
I am using iMac with VirtualBox installed ubuntu 19 Desktop I have installed FFmpeg, Python 3+ and Youtube-dl... What do you think what's the problem? And it does not save videos.

**Comment by oliverjrose99** [comment]
make sure youtube-dl is up to date, run `pip3 install -U youtube-dl` and not the apt command. check the version with `youtube-dl --version`

**Comment by emalov98ffm** [comment]
After I restarted VM all working just fine, thank you!
