### ISSUE TITLE
Manually stop recording

### ISSUE THREAD

**Issue by Karmac** [oliverjrose99/Recordurbate#4]
Is there a way to do so? I tried Ctrl+C but sometimes video files get corrupted.

Thanks.

**Comment by oliverjrose99** [comment]
I'm away right now so I can't test or fix this but try sending sig int to the YouTube dl process that recording. This should stop it properly. Otherwise try putting the file though ffmpeg in copy mode and it should fix the file. tempory until it can properly be added/fixed

**Comment by oliverjrose99** [comment]
Feel free to add random comments and notes if you find any thing
