### ISSUE TITLE
Unable to start, getting recommended Usage error

### ISSUE THREAD

**Issue by monukoshy** [oliverjrose99/Recordurbate#45]
This has been running for me successfully for months, just now, i had to reboot my server, and then i went to start the script.
I use the command and get this error.

webserver@autobot:~/recordurbate$ ./Recordurbate.py start

Usage: Recordurbate [add | del] username
       Recordurbate [start | stop | restart]
       Recordurbate list
       Recordurbate import list.txt
       Recordurbate export [file location]

       Recordurbate help

webserver@autobot:~/recordurbate$

I am in the correct folder.
What do i need to do. I have tried start, stop, help everything, keep getting the same usage pattern notification.

The log file says..

`2020-07-05 04:37:53,320 - loop error
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/usr/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/webserver/recordurbate/bot.py", line 99, in run
    self.logger.info("Stopped recording {}".format(rec[0]))
  File "/usr/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1127, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1033, in emit
    self.handleError(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 946, in handleError
    sys.stderr.write('--- Logging error ---\n')
ValueError: I/O operation on closed file.
2020-07-05 05:11:14,486 - Starting daemon
`

**Comment by oliverjrose99** [comment]
looks like youve run out of storage space

**Comment by monukoshy** [comment]
Thanks for your reply.
But nothing seems out of the blue. have a look at my server storage usage.

```
webserver@autobot:~/recordurbate$ df -h
Filesystem           Size  Used Avail Use% Mounted on
udev                 3.9G     0  3.9G   0% /dev
tmpfs                798M  9.4M  789M   2% /run
/dev/sda3             28G   25G  1.2G  96% /
tmpfs                3.9G     0  3.9G   0% /dev/shm
tmpfs                5.0M     0  5.0M   0% /run/lock
tmpfs                3.9G     0  3.9G   0% /sys/fs/cgroup
//192.168.1.90/CCAM   20T   19T  1.3T  94% /home/webserver/recordurbate/videos
tmpfs                798M   16K  798M   1% /run/user/123
tmpfs                798M     0  798M   0% /run/user/1000
```

**Comment by monukoshy** [comment]
Now it wont even log anything into the rb.log file. The entries are from yesterday afternoon. Today after restarting the server, restarting the services, checking space, restarting server again, restarting recordubate script, no entires in the logs show up.

**Comment by t3rminalx** [comment]
Have you tried deleting rb.pid? That always causes me issues after a reboot.

**Comment by Totonyus** [comment]
I'm pretty sure this is a problem of logging files.

After further investigation I found something could go wrong in this line in some case : https://github.com/oliverjrose99/Recordurbate/blob/dc5f4598d39da9297743c93a514a5044452b718c/recordurbate/daemon.py#L25

I tried to remove all logging references in this file and it starts fine.

**Comment by monukoshy** [comment]
> Have you tried deleting rb.pid? That always causes me issues after a reboot.

I wanted to report back, as you suggested after deleting rb.pid file, the issue was resolved.
Thanks so much for your tips and help.
