### ISSUE TITLE
A tutorial for beginners!

### ISSUE THREAD

**Issue by Arekkusu1998** [oliverjrose99/Recordurbate#56]
As I'm **not** familiar with Python, command line or similar, I cannot figure out how to make recording and / or auto-recording work. Could anyone please explain me better what I need to do? 

- I've a Windows 10 System. 
- I've already installed FFmpeg & youtube-dl (latest versions).
- Now I downloaded Python 3.9.5.
- Now I don't know what to do ... explanations of @oliverjrose99 are obscure for me.

Explanations **for dummies** would be **ideal**. Help me, please: _Idk how to record my favourite performers' sessions_ and the only other choice (CamsBot) is very expensive for me!!

**Comment by oliverjrose99** [comment]
The program/script/thing doesn't work on windows and requires Linux. Please
use either a virtual machine or VPS.

**Comment by Arekkusu1998** [comment]
Ohh, I've understand😢... thank You for the answer.
