### ISSUE TITLE
youtube-dl snapd version

### ISSUE THREAD

**Issue by BiRooT** [oliverjrose99/Recordurbate#57]
Hello,

I prefer to ask here, is youtube-dl snapd version works with your script ? 
Because for me, after adding a user which is streaming to test and then start nothing happens.

For exemple, this user: https://www.youtube.com/c/nicobbq
is streaming right now: https://www.youtube.com/watch?v=XieI7QBaR5U

So I need to add 'nicobbq' in recording list ? 
./Recordurbate.py add nicobbq
./Recordurbate.py start

2021-06-01 16:41:05,910 - Starting daemon
2021-06-01 16:41:05,925 - Successfully started daemon, pid: 1298

Nothing happens, I think I'm missing something.

Thanks for your help :)

**Comment by oliverjrose99** [comment]
dosn't support youtube, only works on CB
