### ISSUE TITLE
No files

### ISSUE THREAD

**Issue by Grimmy347** [oliverjrose99/Recordurbate#6]
I keep doing the run command and it says it started recording but there are no files located in the directory.  Both the youtube and ffmpeg are installed but to no avail.  I have also done apt-get update and upgrade.  Any ideas?

**Comment by Daniel-J-Weaver** [comment]
I had a similar issue because I didn't put the ffmpeg.exe's in the same folder as the youtube-dl.exe.

**Comment by cplaiasu** [comment]
Had a similar issue, in my case was fixed with pip3 install youtube-dl. Looks like apt-get installed it for python 2.7.

**Comment by pinkpanter1001** [comment]
how to run the command ? i added all files like youtube and ffmpeg in one folder too ? how to run it now ?

also it doesnt have any installer ? https://imgur.com/a/5JtIEml

**Comment by oliverjrose99** [comment]
@pinkpanter1001 Sorry I didn't make it very clear but the script is primarily designed and tested to run on linux. At some point i need to redo the config mechanism as well as logging and other bits which should being cross platform support.

**Comment by pinkpanter1001** [comment]
hello is there any option to run in win 7 any other script/Software ? tx

**Comment by oliverjrose99** [comment]
@Grimmy347 Please check syslog to see if apparmor is blocking the process, if so this will be the issue.

**Comment by Grimmy347** [comment]
I installed youtube-dl using pip3 and then it worked.  It just did not want to work installing it through apt-get.

**Comment by Grimmy347** [comment]
Thanks for the help with the install location!

**Comment by OzzWizard** [comment]
same problem but the folder is being created, but it doesn't record video.
