### ISSUE TITLE
start a temporary folder and when the broadcast has finnish move to videos

### ISSUE THREAD

**Issue by francisuk1989** [oliverjrose99/Recordurbate#60]
Great work @oliverjrose99 but have a suggestion for you,

When a user starts to stream, put this into a temporary folder with .part and when the broadcast has finnish move to videos folder, Either by;

Asking, Where dos the user wont the move there complete videos to. e,g my second hard drive
`/media/750gb/videos`

Where shall we keep the temporary streaming videos? e,g for leave blank to save this into this folder.
`/media/80gb/temporary`

**Comment by divenxx** [comment]
--no-part  can be used as youtube dl options to avoid this part file alltogther
