### ISSUE TITLE
Recording lags every 3 seconds

### ISSUE THREAD

**Issue by slilie22** [oliverjrose99/Recordurbate#8]
Hi, I just tried Recordurbate and everything works, but the recorded video is playing 3 seconds smooth and then lags 3 seconds(the frame freezes) and then it plays again smoothly.. are there any recommended specs or anything?

**Comment by oliverjrose99** [comment]
Does it do this with other streamers and other clips, if not it could be on the streamer side. Else I would check things like Internet and storage speed, cpu usage, etc. It is also possible that segments get missed which can't be fixed.

**Comment by slilie22** [comment]
It's really strange... I tried it by using vmware and gave it really much resources, way more than it should need. my hardware specs: i9 9900k, 32gb ram + SSD - recording lags. alright, I try it over at digitalocean.com with the smallest package possible. 1gb ram 1 cpu - recording is smooth.

The only difference is that I tried it with debian 9.8 and at digitalocean I had version 9.7.
What OS are you using?

**Comment by oliverjrose99** [comment]
Ubuntu 18.04 server on a vm with 4CPU/2GB and SSD. Does it continually freeze and then play or just at the start? You can try putting the file through ffmpeg in copy mode and see if it gives you any warnings but the output should then be "fixed"

**Comment by JustForChaturbate** [comment]
Same issue here. But it is not problem of Recordurbate but its a problem of youtube-dl & ffmpeg. I was using it on centos 7.5 and ffmpeg on official relases was only 2.6. When I found out how to update to 4.1 no more lag with ffmpeg-4.1. Also I have lowered download quality in script. It can be done by putting -f slow-2 to command line of youtube-dl (in file bot.py)

**Comment by oliverjrose99** [comment]
@JustForChaturbate Ah thanks, I also found when installing youtube-dl through ubuntu apt that it was very outdated. didn't realise that it was causing an issue.

**Comment by slilie22** [comment]
@oliverjrose99 it does continually freeze, like every 5 seconds.
I just used a buch other mirrors, still no luck... what versions of youtube-dl and ffmpeg are you using?

@JustForChaturbate do you mind sharing how you got your ffmpeg version up to 4.1?

**Comment by JustForChaturbate** [comment]
@slilie22 I just found it in bash history. Sorry, i cant find the source :( - i am using incognito mode for obvious reasons :)) This works for CentOS 7.5, but tutorial was for linux in general:
```
wget https://raw.githubusercontent.com/q3aql/ffmpeg-install/master/ffmpeg-install
chmod a+x ffmpeg-install
sudo ./ffmpeg-install --install relase
```

But it sucks anyway. When I am downloading directly (eg. `./youtube-dl -f slow-2 http://privatecams.com/semulv/`) it works flawlessly. But with this tool it creates just about 3 minutes and then it stops working... :( I would fix it, but there will be DMCA claim on this repo anyway ([like on so many others before](https://www.reddit.com/r/DataHoarder/comments/939s0f/capturebate_alternatives/)), so idk if its worth it :D

**Comment by oliverjrose99** [comment]
@JustForChaturbate Well shit, no idea why, works fine for me but ill try some other stuff. As for the DMCA no idea why mine has lasted this long but we can only hope it stays up.

**Comment by slilie22** [comment]
@JustForChaturbate thank you so much! That ffmpeg install script worked like a charm. Also, thanks for posting how to start a download directly.
About the stop after roughly 3 minutes: It seems to randomly stop recording for me. but after a few seconds it starts again, so not really a big issue for me.

Since my problem got sorted out(thanks again to everyone involved) I will close this issue.
