### ISSUE TITLE
Cannot start the script

### ISSUE THREAD

**Issue by Zeroth42** [oliverjrose99/Recordurbate#81]
Hey everyone,
I installed everything on my RaspBerry Pi 4, but I cannot run the script. When I run it via console "python3 /Recordurbate.py start" it does nothing when I use "add username" it say "line 8 column..." I am new on Python and I dont know what I am making wrong. Can anyone help with a more detailed installation guide for this newbie here :)?

**Comment by divenxx** [comment]
that is exactly the setup i have, i run it on pi4
can you post the exact error you are getting ? 

one possible needed dependency for it to run is youtube-dl 
follow the guide here to get it https://write.corbpie.com/how-to-install-upgrade-youtube-dl-on-ubuntu-20-04/

**Comment by Zeroth42** [comment]
Hey thanks for the answer. I installed yt-dl with command which is given. "pip3 install youtube-dl requests" but I can also try your guide. I can send the error message.

**Comment by Zeroth42** [comment]
![WhatsApp Image 2022-10-06 at 17 20 46](https://user-images.githubusercontent.com/115170602/194352982-6bcbf873-59c9-422a-9eee-127ee14da730.jpeg)
![WhatsApp Image 2022-10-06 at 17 20 47](https://user-images.githubusercontent.com/115170602/194352994-0dc909f1-9abf-4859-8af0-303107ef6b26.jpeg)

**Comment by Zeroth42** [comment]
Here are the photos. I am sure I didnt start the script correctly or using wrong commands. With my current knowledge I cant figure out what I am doing wrong :)

**Comment by divenxx** [comment]
try "./Recordurbate.py start"
or "./Recordurbate add MODEL_1"

**Comment by Zeroth42** [comment]
In the python script? or in the terminal

**Comment by Zeroth42** [comment]
Same error as before
![WhatsApp Image 2022-10-06 at 17 44 12](https://user-images.githubusercontent.com/115170602/194358370-7bf926b0-b7dd-4724-93e2-093da2e8279f.jpeg)
![WhatsApp Image 2022-10-06 at 17 44 12 (1)](https://user-images.githubusercontent.com/115170602/194358381-7cd4765a-4eab-47c4-a3d7-17eda8544216.jpeg)

**Comment by Zeroth42** [comment]
Can you show me how do you set up your downlaoder? What did you make to start it after you downloaded the fresh files from Recordurbate?

**Comment by Zeroth42** [comment]
I figured it out. I was doing mistakes in the wrong order :) now the commands work. Hope I get the dowloads working

**Comment by Zeroth42** [comment]
Now is the problem, that he is not downloading the Stream :( 
Here are shot from the log file
![WhatsApp Image 2022-10-06 at 18 14 07](https://user-images.githubusercontent.com/115170602/194365120-c87885eb-1075-496b-ae7a-0574504acb12.jpeg)
And the terminal:
![WhatsApp Image 2022-10-06 at 18 14 06](https://user-images.githubusercontent.com/115170602/194366008-4ea8bfd9-f6db-441c-931a-5a22f9d36629.jpeg)

**Comment by Zeroth42** [comment]
My problem now is, that the yt-dl is very slow and if I download something it goes to /home/pi instead of the location I choosed

**Comment by divenxx** [comment]
terminal

**Comment by Zeroth42** [comment]
I got it started, but it wont download anything. Can you send me your config details for yt-dl?

**Comment by divenxx** [comment]
for me it looks like this 
![image](https://user-images.githubusercontent.com/103623889/194557222-955b4fd4-72e2-43fd-b2ad-b37dee1b2265.png)
