### ISSUE TITLE
Youtube-dl - WARNING: Failed to download m3u8 information: Remote end closed connection without response ERROR: No video formats found;

### ISSUE THREAD

**Issue by sadpurplebird** [oliverjrose99/Recordurbate#84]
Getting this warning:

`WARNING: Failed to download m3u8 information: Remote end closed connection without response
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

Chaturbate finally DRM?

I was able to get around that error by copying my cookies into the youtube-dl command config. As shown here: 
https://apple.stackexchange.com/questions/349697/how-to-use-youtube-dl-cookies

But then I started getting:
`ERROR: ffmpeg exited with code 1`

**Comment by dvgm506** [comment]
Looks like CB is having issues with their CDN. Web browsers are reverting to JPEG mode. Or at least in NA.
