### ISSUE TITLE
Record after private show finished

### ISSUE THREAD

**Issue by johnwig** [oliverjrose99/Recordurbate#9]
I just realized that this program skip some live. I was watching the show, but this prpgram didn't record it.
So I am wondering can this program record after a private show finished?

**Comment by oliverjrose99** [comment]
Yeah it should be able to, the url it gets the stream location from should
update pretty quickly as its what the Web browser uses and the program
should check every minute. I'll have to test some streams. As a note, The
program doesn't currently support recording private shows.

**Comment by johnwig** [comment]
Oh. Cool to know. Maybe another issue then. Thanks :)
