### ISSUE TITLE
multiple streams

### ISSUE THREAD

**Issue by Scorezy** [oliverjrose99/Recordurbate#91]
Is it somehow possible to download several streams at the same time because I can only download one at a time even though I have added several to the list

**Comment by divenxx** [comment]
this is working for me fine, can you show the log ?

**Comment by Scorezy** [comment]
Unfortunately, I can't look at the log. I've added more than 6 people to the list. Most of the time, however, only one person is reported. I've observed it several times now. But that's not so bad, I have one more question, is it somehow possible to query whether the bot is currently recording a person or not? So via a Discord bot or via a Telegram bot?

**Comment by divenxx** [comment]
you can add some monitoring code to the bot but it doesn't exist natively, the is_online function seems to be the problem 
https://github.com/oliverjrose99/Recordurbate/blob/3c4ea62fcad3d1ec6ab9bc350d84cbb9403102a6/recordurbate/bot.py#L68
you only get results for the top 500 model

**Comment by Scorezy** [comment]
Thank you very much for the quick and uncomplicated answer, so my questions would be answered, I wish you a nice day😊
